MOST_IMPORTANT_REGIONS = {
    'us': 'USA',
    'ru': 'Russian Federation',
    'fr': 'France',
    'de': 'Germany',
    'it': 'Italy',
    'gb': 'UK',
    'tr': 'Turkey',
    'ua': 'Ukraine',
    'kz': 'Kazakhstan',
    'in': 'India',
    'za': 'South Africa'
    }

ALL_REGIONS = {
    'us': 'USA',
    'ru': 'Russian Federation',
    'fr': 'France',
    'de': 'Germany',
    'it': 'Italy',
    'gb': 'UK',
    'mx': 'Mexico',
    'br': 'Brazil',
    'es': 'Spain',
    'tr': 'Turkey',
    'ua': 'Ukraine',
    'ca': 'Canada',
    'au': 'Australia',
    'in': 'India',
    'za': 'South Africa',
    'jp': 'Japan',
    'nl': 'Netherlands',
    'kz': 'Kazakhstan',
    'pl': 'Poland',
    'uz': 'Uzbekistan',
    'be': 'Belgium',
    'cl': 'Chile',
    'ro': 'Romania',
    'co': 'Colombia',
    'ch': 'Switzerland',
    'id': 'Indonesia',
    'ar': 'Argentina',
    'ng': 'Nigeria',
    'il': 'Israel',
    'tw': 'Taiwan',
    'hu': 'Hungary',
    'gr': 'Greece',
    'cz': 'Czechia',
    'at': 'Austria',
    'se': 'Sweden',
    'my': 'Malaysia',
    'pe': 'Peru',
    'pt': 'Portugal',
    'by': 'Belarus',
    'bg': 'Bulgaria',
    'az': 'Azerbaijan',
    'eg': 'Egypt',
    'sa': 'Saudi Arabia',
    'th': 'Thailand',
    'ma': 'Morocco',
    'kg': 'Kyrgyzstan',
    'ec': 'Ecuador',
    'kr': 'Korea',
    'dk': 'Denmark'
}