"""Youtube model fixed a bit

Revision ID: 41075e817a8d
Revises: 8d04bb04bf70
Create Date: 2023-08-05 10:27:17.221396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41075e817a8d'
down_revision = '8d04bb04bf70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('youtube_trackmatch_yt_metadata_key', 'youtube_trackmatch', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('youtube_trackmatch_yt_metadata_key', 'youtube_trackmatch', ['yt_metadata'])
    # ### end Alembic commands ###
