"""Youtube model update, channel name added

Revision ID: 7e49c595240c
Revises: 41075e817a8d
Create Date: 2023-08-07 15:12:18.396749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e49c595240c'
down_revision = '41075e817a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_trackmatch', sa.Column('channel_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_trackmatch', 'channel_name')
    # ### end Alembic commands ###
