"""Added some extra fields to Playlist model

Revision ID: 8d04bb04bf70
Revises: b64b967f0316
Create Date: 2023-08-05 09:48:06.341323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d04bb04bf70'
down_revision = 'b64b967f0316'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('original_metadata', sa.String(), nullable=False))
    op.add_column('playlists', sa.Column('artist', sa.String(), nullable=False))
    op.add_column('playlists', sa.Column('track_title', sa.String(), nullable=False))
    op.add_column('playlists', sa.Column('release_id', sa.UUID(), nullable=False))
    op.add_column('playlists', sa.Column('from_chart', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'from_chart')
    op.drop_column('playlists', 'release_id')
    op.drop_column('playlists', 'track_title')
    op.drop_column('playlists', 'artist')
    op.drop_column('playlists', 'original_metadata')
    # ### end Alembic commands ###
