"""Release data isrc dropped as currently not needed

Revision ID: af2ce723522a
Revises: c714f7a3c98d
Create Date: 2023-07-31 15:13:38.821092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2ce723522a'
down_revision = 'c714f7a3c98d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('music_releases_release_isrc_key', 'music_releases', type_='unique')
    op.drop_column('music_releases', 'release_isrc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_releases', sa.Column('release_isrc', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint('music_releases_release_isrc_key', 'music_releases', ['release_isrc'])
    # ### end Alembic commands ###
