"""Added playlist id in Playlist model and optional name for a playlist

Revision ID: b64b967f0316
Revises: 2bb10d4f674f
Create Date: 2023-08-04 21:07:41.338767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64b967f0316'
down_revision = '2bb10d4f674f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('playlist_id', sa.UUID(), nullable=False))
    op.add_column('playlists', sa.Column('playlist_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'playlist_name')
    op.drop_column('playlists', 'playlist_id')
    # ### end Alembic commands ###
