"""Release data collection updated

Revision ID: c714f7a3c98d
Revises: cee96110d81d
Create Date: 2023-07-31 15:10:45.895972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c714f7a3c98d'
down_revision = 'cee96110d81d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_releases', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('music_releases', sa.Column('in_num_charts', sa.Integer(), nullable=True))
    op.add_column('music_releases', sa.Column('total_ranking', sa.Integer(), nullable=True))
    op.add_column('music_releases', sa.Column('num_ratings', sa.Integer(), nullable=True))
    op.add_column('music_releases', sa.Column('top_percentile', sa.Float(), nullable=True))
    op.add_column('music_releases', sa.Column('bayes_avg_rating', sa.Float(), nullable=True))
    op.add_column('music_releases', sa.Column('mean_avg_rating', sa.Float(), nullable=True))
    op.add_column('music_releases', sa.Column('std_rating', sa.Float(), nullable=True))
    op.add_column('music_releases', sa.Column('num_favourites', sa.Integer(), nullable=True))
    op.drop_column('music_releases', 'release_country')
    op.drop_column('music_releases', 'appears_in_num_charts')
    op.drop_column('music_releases', 'risky_metadata')
    op.drop_column('music_releases', 'release_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_releases', sa.Column('release_duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.add_column('music_releases', sa.Column('risky_metadata', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('music_releases', sa.Column('appears_in_num_charts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('music_releases', sa.Column('release_country', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('music_releases', 'num_favourites')
    op.drop_column('music_releases', 'std_rating')
    op.drop_column('music_releases', 'mean_avg_rating')
    op.drop_column('music_releases', 'bayes_avg_rating')
    op.drop_column('music_releases', 'top_percentile')
    op.drop_column('music_releases', 'num_ratings')
    op.drop_column('music_releases', 'total_ranking')
    op.drop_column('music_releases', 'in_num_charts')
    op.drop_column('music_releases', 'release_date')
    # ### end Alembic commands ###
